### ISSUE TITLE
Failing to import python swig wrapper

### ISSUE THREAD

**Issue by rafaellago** [thp/psmoveapi#225]
I ran swig on the binding folder and managed to generate a psmove.py file. Then created a simple script only with the imports and used the examples to attempt to do it right. But I get an error when trying to import the psmove file. 

In my project dir, it haves the api.dll, the psmove.py and my script.

the script is as follows:
```python
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'build'))

import time
import psmove

print("Import succesfull")
```

but then I get these errors when trying to run:

```
C:\Users\Rafael\Desktop\pymove>bridge.py
Traceback (most recent call last):
  File "C:\Users\Rafael\Desktop\pymove\psmove.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_psmove', [dirname(__file__)])
  File "C:\Python\Python35\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_psmove'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rafael\Desktop\pymove\bridge.py", line 6, in <module>
    import psmove
  File "C:\Users\Rafael\Desktop\pymove\psmove.py", line 28, in <module>
    _psmove = swig_import_helper()
  File "C:\Users\Rafael\Desktop\pymove\psmove.py", line 20, in swig_import_helper
    import _psmove
ImportError: No module named '_psmove'
```

Has anyone gone through this? what could I do?

**Comment by rafaellago** [comment]
Managed to run it using a simple ctypes dll import

```python
from ctypes import *

moveapi = windll.libpsmoveapi
moveapi.psmove_init(0x030901) #Was using moveapi v 3.9.1
controller = moveapi.psmove_connect()

#From there is just fun
```
