### ISSUE TITLE
psmove errors in raspian buster.

### ISSUE THREAD

**Issue by adangert** [thp/psmoveapi#387]
After what looks like successfully compiling the psmoveapi on buster, the following error occurs when trying to start the api:

```
Traceback (most recent call last):
  File "/home/pi/psmoveapi/build/psmove.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/pi/JoustMania/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/pi/psmoveapi/build/_psmove.so: undefined symbol: psmove_tracker_get_image

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/JoustMania/piparty.py", line 1, in <module>
    import psmove
  File "/home/pi/psmoveapi/build/psmove.py", line 17, in <module>
    _psmove = swig_import_helper()
  File "/home/pi/psmoveapi/build/psmove.py", line 16, in swig_import_helper
    return importlib.import_module('_psmove')
  File "/home/pi/JoustMania/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/pi/psmoveapi/build/_psmove.so: undefined symbol: psmove_tracker_get_image

```

**Comment by adangert** [comment]
the regular psmove executable works, it seems like it's just the python swig integration that is having problems.

**Comment by adangert** [comment]
So I believe I have found the issue, libopencv-dev on buster now installs opencv version 3.2 therefore https://github.com/thp/psmoveapi/blob/master/src/tracker/CMakeLists.txt#L31 can not find the library.
