### ISSUE TITLE
PyCharm Windows 10: ImportError: DLL load failed while importing _psmove: The specified module could not be found.

### ISSUE THREAD

**Issue by a-eye-tech** [thp/psmoveapi#445]
I downloaded the prebuilt library and I added this to my Windows 10 Path:

```
PYTHONPATH
C:\Users\user\Desktop\psmoveapi-4.0.12-windows-msvc2017-x64\bindings\python

PSMOVEAPI_LIBRARY_PATH
C:\Users\user\Desktop\psmoveapi-4.0.12-windows-msvc2017-x64\lib
```
When I run a copy of always.py in a new PyCharm project or run always.py from command prompt, I get this error:
```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\psmoveapi-4.0.12-windows-msvc2017-x64\bindings\python\psmove.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing _psmove: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\PSMove\main.py", line 36, in <module>
    import psmove
  File "C:\Users\user\Desktop\psmoveapi-4.0.12-windows-msvc2017-x64\bindings\python\psmove.py", line 17, in <module>
    _psmove = swig_import_helper()
  File "C:\Users\user\Desktop\psmoveapi-4.0.12-windows-msvc2017-x64\bindings\python\psmove.py", line 16, in swig_import_helper
    return importlib.import_module('_psmove')
  File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _psmove: The specified module could not be found.
```
Can someone please help me? 

I confirmed that there is a file, '_psmove.pyd', in my PYTHONPATH.

**Comment by a-eye-tech** [comment]
Ok, I finally got it to work on Python PyCharm Windows 10. This is what I did:

**Git**
Get clone link.
Right click on an empty folder, and 'Git Bash Here'
Enter, 'git clone' and paste link.
One clone directory, 'Git Bash Here' 
Enter 'git submodule update --init --recursive'. You may need to do this a few times.

**Edit build_msvc.bat**
Remote the sections '^(Debug^)' for OpenCV and PS Move API
Add Add -DPSMOVE_BUILD_PYTHON_BINDINGS=1 to end of this line:
`cmake .. -G "%MSVC_CMAKE_GENERATOR%" -DPSMOVE_USE_PS3EYE_DRIVER=1 -DPSMOVE_BUILD_OPENGL_EXAMPLES=1 -DOpenCV_DIR=./external/opencv/build-%MSVC_PLATFORM%/`

**Developer Command Prompt 2017**
Enter 'cd <your psmoveapi clone directory>'
Enter 'call scripts/visualc/build_msvc.bat 2017 x64'

**Add to Windows 10 Paths**
PYTHONPATH: <your path to>psmoveapi\build-x64
PSMOVEAPI_LIBRARY_PATH: <your path to>psmoveapi\build-x64
Add to Path: <your path to>psmoveapi\build-x64
